timer: 10
radius: 10
cancelOn:
  playerPVP: true
  move: true
  mobDamage: true
globalWarpsCountTowardsTotal: false
defaultMaxWarps: 50
warpInviteTimeout: 120
useMultiverse: true
warpListPages: true
defaultToPublicWarp: true
forceCommandOverride:
  warp: false
  delwarp: false
  setwarp: false